### ISSUE TITLE
Hello!

### ISSUE THREAD

**Issue by cccs-rs** [NVISOsecurity/assemblyline-service-document-preview#2]
We (Assemblyline Team) are interested in making your service as part of our official service offerings for ALv4.

If you'd like, we can transfer ownership of the service to us and we can manage and maintain the service for you!

Let us know what you think. 😀

**Comment by cccs-rs** [comment]
@Sorakurai @x1mus @jvanwilder  -  I'd love to hear your feedback on this!

We're looking to also add preview of emails to the service and using ImageResultSections to preview all images rather than limit to 1 or N (but could be used for adding to extracted).

We have lots of ideas for this service!

**Comment by x1mus** [comment]
Hello ! If it was up to me, I'd love to see the service implemented in the official services offered in ALv4 but since it's not only up to me the feedbacks from NVISO (@Sorakurai / @jvanwilder ) is for sure required.

**Comment by Sorakurai** [comment]
Hi Assemblyline Team, we'd love to see this grow further and see it incorporated into the official offering! Could you reach out to research@nviso.eu to discuss practical steps? ;)

**Comment by cccs-rs** [comment]
Sent! 📨

**Comment by cccs-jp** [comment]
Hi @jvanwilder , can you transfer the repository to me. Thanks

**Comment by jvanwilder** [comment]
Hi @cccs-jp, ownership transfer is already started, so you should be able to accept it.

**Comment by cccs-jp** [comment]
Hi again! :) Would you be able to re-initiate it? There is no notification about it on my side.

**Comment by jvanwilder** [comment]
Hi, I re-initiated it and it should have sent a repository transfer request.
